### ISSUE TITLE
Congrats on 1.0! Noticed broken link in your blog post.

### ISSUE THREAD

**Issue by blakeNaccarato** [martinfleis/martinfleis.github.io#1]
On the line below, that link 404s for some reason. Seems like the correct link, but it's 404ing for me all the same? Maybe it's a minor typo I'm not picking up at a glance, or something happening at build time that's botching the link.

https://github.com/martinfleis/martinfleis.github.io/blob/5e153da75ec897006a836ac88c153fd0cf8cd8cd/content/posts/geopandas-1.md?plain=1#L60

**Comment by martinfleis** [comment]
Thanks!
